# Generated by Django 6.0.6 on 2026-08-22 06:15

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_weight_kg',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_restrictions',
            field=models.JSONField(default=apps.profiles.models.default_health_restrictions),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_restrictions',
            field=models.JSONField(default=apps.profiles.models.default_social_restrictions),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.CharField(choices=[('VEGETARIAN', 'Vegetarian'), ('NON_VEGETARIAN', 'Non Vegetarian'), ('EGGITARIAN', 'Eggitarian / Egg only')], default='NON_VEGETARIAN', max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fitness_goal',
            field=models.CharField(choices=[('LOSE_WEIGHT', 'Lose Weight'), ('MAINTAIN_WEIGHT', 'Maintain Weight'), ('BUILD_MUSCLE', 'Build Muscle')], default='MAINTAIN_WEIGHT', max_length=30),
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
    ]
