# -*- coding: utf-8 -*-
"""final_minor_project_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mV9hBG8M18aoHmleeK0XHQ2eG5afKYug
"""

# this code was used to train one of the versions (not final one)

# Check GPU availability and install latest Ultralytics package
!nvidia-smi
!pip install -q ultralytics

from google.colab import files
import zipfile
import os

# Prompt file upload from local machine
print("Please select your nepali_dal_bhat_dataset.zip file:")
uploaded = files.upload()

zip_name = list(uploaded.keys())[0]

# Extract directly into Colab runtime storage
with zipfile.ZipFile(zip_name, 'r') as zip_ref:
    zip_ref.extractall('/content')

print("Dataset uploaded and extracted successfully to /content!")

import yaml

# Overwrite data.yaml in the correct dataset folder
yaml_content = {
    'path': '/content/final_yolo_model_dataset',
    'train': 'images/train',
    'val': 'images/val',
    'names': {
        0: 'bhat',
        1: 'dal',
        2: 'sabji'
    }
}

with open('/content/final_yolo_model_dataset/data.yaml', 'w') as f:
    yaml.dump(yaml_content, f, default_flow_style=False)

print("data.yaml successfully created in /content/final_yolo_model_dataset!")

from ultralytics import YOLO

model = YOLO("yolo11n-seg.pt")

results = model.train(
    data="/content/final_yolo_model_dataset/data.yaml", # Updated path here
    task="segment",
    epochs=100,
    imgsz=640,
    batch=16,
    workers=8,
    patience=30,

    # Optimization
    optimizer="AdamW",
    lr0=0.002,
    lrf=0.01,
    cos_lr=True,
    weight_decay=0.0005,

    # Augmentations
    augment=True,
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,
    degrees=10.0,
    translate=0.1,
    scale=0.5,
    shear=0.0,
    perspective=0.0001,
    flipud=0.0,
    fliplr=0.5,
    mosaic=1.0,
    mixup=0.0,

    project="/content/runs/segment",
    name="nepali_plate_final_run",
    exist_ok=True
)

from google.colab import files

files.download('/content/runs/segment/nepali_plate_final_run/weights/best.pt')

from google.colab import files
import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO

# 1. Load your fine-tuned segmentation model
model = YOLO('/content/runs/segment/nepali_plate_final_run/weights/best.pt')

# 2. Upload an image from your computer
uploaded = files.upload()

# 3. Predict on the uploaded image
for file_name in uploaded.keys():
    # Run inference with a confidence threshold
    results = model.predict(source=file_name, conf=0.25)

    # Render the segmentation masks and bounding boxes onto the image
    res_plotted = results[0].plot()

    # Convert BGR (OpenCV format) to RGB for Matplotlib display
    res_rgb = cv2.cvtColor(res_plotted, cv2.COLOR_BGR2RGB)

    # Display the result
    plt.figure(figsize=(10, 10))
    plt.imshow(res_rgb)
    plt.axis('off')
    plt.show()

import cv2
import numpy as np

# 1. Reference dimensions (assuming standard plate diameter = 28 cm)
KNOWN_PLATE_DIAMETER_CM = 28.0

# 2. Food physical properties (Density in g/cm3, Estimated average height in cm)
FOOD_PROPERTIES = {
    'bhat':  {'density': 0.75, 'avg_height_cm': 3.5, 'shape': 'dome'},
    'dal':   {'density': 1.05, 'avg_height_cm': 4.0, 'shape': 'cylinder'},
    'sabji': {'density': 0.90, 'avg_height_cm': 2.0, 'shape': 'flat'}
}

results = model.predict(source="6a449b8a-261.jpg", conf=0.25)
res = results[0]

# Estimate pixel scale using bounding box width/height of full plate or largest object
# For best results, detect the plate rim. Here we approximate scale from image dimensions:
img_h, img_w = res.orig_shape
plate_pixel_diameter = min(img_h, img_w) * 0.85 # Estimated plate pixel width
cm_per_pixel = KNOWN_PLATE_DIAMETER_CM / plate_pixel_diameter
sq_cm_per_pixel = cm_per_pixel ** 2

if res.masks is not None:
    masks = res.masks.data.cpu().numpy()
    classes = res.boxes.cls.cpu().numpy()
    names = res.names

    total_weights = {}

    for i, mask in enumerate(masks):
        cls_name = names[int(classes[i])]

        # Resize mask to original image size
        mask_resized = cv2.resize(mask, (img_w, img_h)) > 0.5
        pixel_area = np.sum(mask_resized)
        area_sq_cm = pixel_area * sq_cm_per_pixel

        # Retrieve density and height
        prop = FOOD_PROPERTIES.get(cls_name, {'density': 0.85, 'avg_height_cm': 2.0, 'shape': 'flat'})

        # Calculate volume based on shape approximation
        if prop['shape'] == 'dome':
            # Hemisphere/Dome approximation: V = 0.6 * Area * Height
            volume_cm3 = 0.6 * area_sq_cm * prop['avg_height_cm']
        else:
            volume_cm3 = area_sq_cm * prop['avg_height_cm']

        weight_grams = volume_cm3 * prop['density']

        total_weights[cls_name] = total_weights.get(cls_name, 0) + weight_grams

    # Print Estimated Results
    print("--- Estimated Food Quantities ---")
    for item, weight in total_weights.items():
        print(f"{item.capitalize()}: ~{weight:.1f} grams")

import os

# Path to the best trained weights
best_model_path = "/content/runs/segment/nepali_plate_final_run/weights/best.pt"

if os.path.exists(best_model_path):
    size_mb = os.path.getsize(best_model_path) / (1024 * 1024)
    print(f"Final Model Saved: {best_model_path}")
    print(f"Model File Size: {size_mb:.2f} MB")
else:
    print("Training finished. Check runs directory for output.")