# -*- coding: utf-8 -*-
"""IMPORTANT_final_colab_file_minor_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zH8V5v9jlx_K-avpdy3VYcvvEiPffqE3
"""

# this is the final IMPORTANT code used to train can calcualte metrices

# Verify GPU availability and install the latest Ultralytics release with visualization dependencies
!nvidia-smi
!pip install -q ultralytics matplotlib seaborn pandas

import zipfile
import os
from google.colab import files

print("Please upload your dataset zip file (e.g., final_yolo_model_dataset.zip):")
uploaded = files.upload()

zip_name = list(uploaded.keys())[0]

# Extract directly into /content runtime
with zipfile.ZipFile(zip_name, 'r') as zip_ref:
    zip_ref.extractall('/content')

print(f"Successfully extracted {zip_name} to /content!")

import yaml

# Automatically set up data.yaml with optimized absolute paths
yaml_content = {
    'path': '/content/final_yolo_model_dataset',
    'train': 'images/train',
    'val': 'images/val',
    'names': {
        0: 'bhat',
        1: 'dal',
        2: 'sabji'
    }
}

yaml_path = '/content/final_yolo_model_dataset/data.yaml'
with open(yaml_path, 'w') as f:
    yaml.dump(yaml_content, f, default_flow_style=False)

print(f"data.yaml configured successfully at {yaml_path}!")

from ultralytics import YOLO

# Load lightweight YOLO11 Nano Segmentation model
model = YOLO("yolo11n-seg.pt")

# Fine-tuned training pipeline engineered for small dataset sizes (~300 images)
results = model.train(
    data="/content/final_yolo_model_dataset/data.yaml",
    task="segment",
    epochs=120,
    imgsz=640,
    batch=16,
    workers=4,
    patience=25,

    # Optimization strategy
    optimizer="AdamW",
    lr0=0.0015,
    lrf=0.01,
    cos_lr=True,
    weight_decay=0.0005,

    # Strategic augmentation suite tailored for food plate segmentation
    augment=True,
    hsv_h=0.015,
    hsv_s=0.6,
    hsv_v=0.4,
    degrees=15.0,
    translate=0.1,
    scale=0.5,
    shear=2.0,
    perspective=0.0001,
    flipud=0.0,
    fliplr=0.5,
    mosaic=1.0,
    mixup=0.1,
    copy_paste=0.1,

    # Output tracking
    project="/content/runs/segment",
    name="nepali_plate_optimized_run",
    exist_ok=True,
    plots=True
)

import matplotlib.pyplot as plt
import cv2
from PIL import Image

run_dir = "/content/runs/segment/nepali_plate_optimized_run"

# Display training loss and metric curves
results_png = os.path.join(run_dir, "results.png")
if os.path.exists(results_png):
    plt.figure(figsize=(12, 8))
    plt.imshow(Image.open(results_png))
    plt.axis("off")
    plt.title("Training Loss & Metric Curves", fontsize=14)
    plt.show()

# Display Confusion Matrix
confusion_png = os.path.join(run_dir, "confusion_matrix.png")
if os.path.exists(confusion_png):
    plt.figure(figsize=(8, 8))
    plt.imshow(Image.open(confusion_png))
    plt.axis("off")
    plt.title("Normalized Confusion Matrix", fontsize=14)
    plt.show()

# Display Validation Predictions
val_batch = os.path.join(run_dir, "val_batch0_pred.jpg")
if os.path.exists(val_batch):
    plt.figure(figsize=(10, 10))
    plt.imshow(Image.open(val_batch))
    plt.axis("off")
    plt.title("Validation Batch Ground Truth vs Predictions", fontsize=14)
    plt.show()

import os
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image

run_dir = "/content/runs/segment/nepali_plate_optimized_run"

# 1. PRINT NUMERICAL METRICS TABLE
results_csv = os.path.join(run_dir, "results.csv")

if os.path.exists(results_csv):
    df = pd.read_csv(results_csv)
    df.columns = df.columns.str.strip()  # Strip extra spaces from column names

    print("="*60)
    print("FINAL MODEL ACCURACY METRICS (Last Epoch):")
    print("="*60)

    # Extract latest performance metrics
    last_epoch = df.iloc[-1]

    # Bounding Box / Detection Metrics
    if 'metrics/precision(B)' in df.columns:
        print(f"Box Precision (B):    {last_epoch['metrics/precision(B)']:.4f}")
        print(f"Box Recall (B):       {last_epoch['metrics/recall(B)']:.4f}")
        print(f"Box mAP50 (B):        {last_epoch['metrics/mAP50(B)']:.4f}")
        print(f"Box mAP50-95 (B):     {last_epoch['metrics/mAP50-95(B)']:.4f}")
        print("-" * 60)

    # Mask / Segmentation Metrics
    if 'metrics/precision(M)' in df.columns:
        print(f"Mask Precision (M):   {last_epoch['metrics/precision(M)']:.4f}")
        print(f"Mask Recall (M):      {last_epoch['metrics/recall(M)']:.4f}")
        print(f"Mask mAP50 (M):       {last_epoch['metrics/mAP50(M)']:.4f}")
        print(f"Mask mAP50-95 (M):    {last_epoch['metrics/mAP50-95(M)']:.4f}")
        print("="*60)

# 2. DISPLAY TRAINING & VALIDATION GRAPH (results.png)
results_png = os.path.join(run_dir, "results.png")
if os.path.exists(results_png):
    plt.figure(figsize=(16, 10))
    plt.imshow(Image.open(results_png))
    plt.axis("off")
    plt.title("Training Loss & Performance Curves (results.png)", fontsize=16, pad=12)
    plt.show()

# 3. DISPLAY ADDITIONAL EVALUATION CHARTS
additional_plots = [
    ("confusion_matrix.png", "Confusion Matrix"),
    ("PR_curve.png", "Precision-Recall Curve"),
    ("F1_curve.png", "F1 Confidence Curve")
]

for file_name, title in additional_plots:
    img_path = os.path.join(run_dir, file_name)
    if os.path.exists(img_path):
        plt.figure(figsize=(10, 8))
        plt.imshow(Image.open(img_path))
        plt.axis("off")
        plt.title(title, fontsize=14, pad=10)
        plt.show()

import os
from google.colab import files

# Path to the best weights generated from your training run
model_path = "/content/runs/segment/nepali_plate_optimized_run/weights/best.pt"

if os.path.exists(model_path):
    print("Downloading best.pt to your local machine...")
    files.download(model_path)
else:
    print(f"Model file not found at {model_path}. Ensure training completed successfully.")

from ultralytics import YOLO  # Load YOLO library

# Load lightweight YOLO11 Nano Segmentation model
model = YOLO("yolo11n-seg.pt")  # Load pre-trained weights

# Fine-tuned training pipeline engineered for small dataset sizes (~300 images)
results = model.train(  # Start training process
    data="/content/final_yolo_model_dataset/data.yaml",  # Dataset config path
    task="segment",  # Instance segmentation task
    epochs=120,  # Max training cycles
    imgsz=640,  # Image resolution
    batch=16,  # Batch size
    workers=4,  # CPU data loaders
    patience=25,  # Early stopping limit

    # Optimization strategy
    optimizer="AdamW",  # AdamW optimizer
    lr0=0.0015,  # Initial learning rate
    lrf=0.01,  # Final learning rate ratio
    cos_lr=True,  # Cosine learning schedule
    weight_decay=0.0005,  # Weight decay penalty

    # Strategic augmentation suite tailored for food plate segmentation
    augment=True,  # Enable augmentations
    hsv_h=0.015,  # Hue variation
    hsv_s=0.6,  # Saturation variation
    hsv_v=0.4,  # Brightness variation
    degrees=15.0,  # Rotation angle
    translate=0.1,  # Image translation shift
    scale=0.5,  # Zoom scale factor
    shear=2.0,  # Shear distortion angle
    perspective=0.0001,  # Perspective shift angle
    flipud=0.0,  # Vertical flip chance
    fliplr=0.5,  # Horizontal flip chance
    mosaic=1.0,  # 4-image mosaic mix
    mixup=0.1,  # Image mixup probability
    copy_paste=0.1,  # Mask copy-paste chance

    # Output tracking
    project="/content/runs/segment",  # Save folder location
    name="nepali_plate_optimized_run",  # Run folder name
    exist_ok=True,  # Overwrite existing folder
    plots=True  # Generate metric plots
)