# -*- coding: utf-8 -*-
"""YOLO_nepali_food_dummy_data_testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lJEpJCP4TPA3jeT0CZcOVVeqWATcgmT8
"""

# this code is for testing yolo on a dummy dataset

"""GPU check and library Installation"""

# Check GPU availability and install Ultralytics
!nvidia-smi
!pip install -q ultralytics

"""uploading the zip

"""

from google.colab import files
import zipfile
import os

# Prompt file upload from local machine
print("Please select your nepali_dal_bhat_dataset.zip file:")
uploaded = files.upload()

zip_name = list(uploaded.keys())[0]

# Extract directly into Colab runtime storage
with zipfile.ZipFile(zip_name, 'r') as zip_ref:
    zip_ref.extractall('/content')

print("Dataset uploaded and extracted successfully to /content!")

"""run this this will overwrite the data.ymal in your zip file as it is most likely has a faulty path"""

import yaml

# Overwrite data.yaml with Colab-compatible paths
yaml_content = {
    'path': '/content/nepali_dal_bhat_dataset',
    'train': 'images/train',
    'val': 'images/val',
    'names': {
        0: 'bhat',
        1: 'dal',
        2: 'sabji'
    }
}

with open('/content/nepali_dal_bhat_dataset/data.yaml', 'w') as f:
    yaml.dump(yaml_content, f, default_flow_style=False)

print("data.yaml updated with Colab paths successfully!")

"""train yolov8 with advanced data agumentation"""

from ultralytics import YOLO

# Load lightweight segmentation model (~7MB)
model = YOLO("yolov8n-seg.pt")

# Train with aggressive data augmentations
results = model.train(
    data="/content/nepali_dal_bhat_dataset/data.yaml",
    task="segment",
    epochs=100,             # High epoch count for small dataset convergence
    imgsz=640,
    batch=16,

    # Advanced Data Augmentations
    augment=True,
    hsv_h=0.015,            # Color hue variation
    hsv_s=0.7,              # Saturation variation
    hsv_v=0.4,              # Brightness variation
    degrees=15.0,           # Random rotations
    translate=0.1,          # Image translation
    scale=0.5,              # Random scaling
    shear=2.0,              # Geometric shear
    perspective=0.0005,     # Perspective transform
    flipud=0.5,             # Vertical flip
    fliplr=0.5,             # Horizontal flip
    mosaic=1.0,             # Mosaic augmentation (combines 4 images into 1)
    mixup=0.1,              # Blends images together

    # Save training output locally in Colab runtime
    project="/content/runs/segment",
    name="nepali_plate_run"
)

"""this below fucntoin inferences on test images and calcualtes the exact segmented area in pixels and relative plate percentage for bhat, dal and sabji"""

import glob

# Search for best.pt inside /content/runs
found_weights = glob.glob("/content/runs/**/best.pt", recursive=True)

if found_weights:
    print("Found best.pt at:")
    for path in found_weights:
        print(path)
else:
    print("best.pt was not found. Please verify if model.train() finished running successfully.")

import cv2
import glob
import numpy as np
import os
from ultralytics import YOLO

# Dynamically pick the generated best.pt path
weights = glob.glob("/content/runs/**/best.pt", recursive=True)

if not weights:
    raise FileNotFoundError("Training has not finished or best.pt does not exist yet. Run model.train() first.")

best_model_path = weights[0]
print(f"Loading weights from: {best_model_path}")
model = YOLO(best_model_path)

def analyze_plate(image_path):
    results = model.predict(source=image_path, conf=0.25, task="segment")
    result = results[0]

    img_height, img_width = result.orig_shape

    summary = {
        "bhat": {"pixel_count": 0, "percentage": 0.0},
        "dal": {"pixel_count": 0, "percentage": 0.0},
        "sabji": {"pixel_count": 0, "percentage": 0.0}
    }

    if result.masks is not None:
        masks = result.masks.data.cpu().numpy()  # shape: (N, H, W)
        class_ids = result.boxes.cls.cpu().numpy().astype(int)

        for mask, cls_id in zip(masks, class_ids):
            class_name = result.names[cls_id]

            # Resize binary mask to original image dimensions
            resized_mask = cv2.resize(mask, (img_width, img_height))
            binary_mask = (resized_mask > 0.5).astype(np.uint8)

            # Count positive mask pixels
            pixel_area = int(np.sum(binary_mask))

            if class_name in summary:
                summary[class_name]["pixel_count"] += pixel_area

        # Calculate percentage distribution across plate
        total_food_pixels = sum(item["pixel_count"] for item in summary.values())
        if total_food_pixels > 0:
            for item in summary:
                summary[item]["percentage"] = round((summary[item]["pixel_count"] / total_food_pixels) * 100, 2)

    return summary

# Test execution on a validation image
val_dir = "/content/nepali_dal_bhat_dataset/images/val"
sample_img = os.path.join(val_dir, os.listdir(val_dir)[0])
food_payload = analyze_plate(sample_img)

print("\nSegmented Quantities Payload for Downstream Module:")
print(food_payload)

"""downling trained weights"""

import glob
from google.colab import files

# Search for best.pt dynamically
found_weights = glob.glob("/content/runs/**/best.pt", recursive=True)

if found_weights:
    target_weight = found_weights[0]
    print(f"Found model weights at: {target_weight}")
    print("Initiating download...")
    files.download(target_weight)
else:
    print("❌ Could not find 'best.pt'. Please ensure your model.train() cell ran and completed successfully.")

"""Evaluation

"""

import cv2
import glob
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from ultralytics import YOLO

# 1. Locate and load the trained model weights dynamically
weights = glob.glob("/content/runs/**/best.pt", recursive=True)
if not weights:
    raise FileNotFoundError("Could not find 'best.pt'. Make sure training completed successfully.")

best_model_path = weights[0]
print(f"Loading weights from: {best_model_path}")
model = YOLO(best_model_path)

# 2. Upload image from local device
print("\nUpload an image from your device to test segmentation:")
uploaded = files.upload()

if uploaded:
    image_name = list(uploaded.keys())[0]

    # 3. Run YOLOv8 Segmentation Inference
    results = model.predict(source=image_name, conf=0.25, task="segment")
    result = results[0]

    # 4. Generate Visual Overlay Plot
    annotated_frame = result.plot()  # Draws segmentation masks, boxes, and labels

    plt.figure(figsize=(10, 10))
    plt.imshow(cv2.cvtColor(annotated_frame, cv2.COLOR_BGR2RGB))
    plt.title("YOLOv8 Segmentation Overlay", fontsize=14, fontweight='bold')
    plt.axis('off')
    plt.show()

    # 5. Compute Quantitative Metrics Payload
    img_h, img_w = result.orig_shape
    total_pixels = img_h * img_w

    summary = {
        "bhat": {"count": 0, "max_conf": 0.0, "pixel_area": 0},
        "dal": {"count": 0, "max_conf": 0.0, "pixel_area": 0},
        "sabji": {"count": 0, "max_conf": 0.0, "pixel_area": 0}
    }

    if result.masks is not None and result.boxes is not None:
        masks = result.masks.data.cpu().numpy()
        class_ids = result.boxes.cls.cpu().numpy().astype(int)
        confs = result.boxes.conf.cpu().numpy()

        for mask, cls_id, conf in zip(masks, class_ids, confs):
            class_name = result.names[cls_id]

            # Resize binary mask to original image dimensions
            resized_mask = cv2.resize(mask, (img_w, img_h))
            binary_mask = (resized_mask > 0.5).astype(np.uint8)
            pixel_area = int(np.sum(binary_mask))

            if class_name in summary:
                summary[class_name]["count"] += 1
                summary[class_name]["pixel_area"] += pixel_area
                summary[class_name]["max_conf"] = max(summary[class_name]["max_conf"], float(conf))

    # Calculate relative percentage distribution
    total_food_pixels = sum(item["pixel_area"] for item in summary.values())

    print("\n" + "="*50)
    print("      EVALUATION METRICS & SEGMENTATION BREAKDOWN")
    print("="*50)
    print(f"Original Image Dimensions : {img_w}x{img_h} ({total_pixels:,} total pixels)")
    print(f"Total Food Area Segmented : {total_food_pixels:,} pixels\n")

    print(f"{'Class':<10} | {'Detections':<10} | {'Confidence':<12} | {'Pixel Area':<12} | {'Plate Share (%)':<15}")
    print("-" * 68)

    for item_name, data in summary.items():
        conf_str = f"{data['max_conf']*100:.1f}%" if data['count'] > 0 else "N/A"
        pct_share = round((data['pixel_area'] / total_food_pixels) * 100, 2) if total_food_pixels > 0 else 0.0

        print(f"{item_name:<10} | {data['count']:<10} | {conf_str:<12} | {data['pixel_area']:<12,} | {pct_share}%")

    print("="*50)

