# Generated by Django 6.0.6 on 2026-08-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_mealrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], default='LUNCH', max_length=25),
        ),
    ]
