# Generated by Django 6.0.6 on 2026-08-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_meallog_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealfooditems',
            name='micronutrients',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='totalfoodanalysis',
            name='micronutrients',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
