# Generated by Django 6.0.6 on 2026-07-26 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=25)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity_level', models.CharField(choices=[('SEDENTARY', 'Sedentary'), ('LIGHT', 'Lightly Active'), ('MODERATE', 'Moderately Active'), ('VERY_ACTIVE', 'Very Active'), ('ATHLETE', 'Athlete')], default='SEDENTARY', max_length=25)),
                ('fitness_goal', models.CharField(choices=[('LOSE_WEIGHT', 'Lose Weight'), ('MAINTAIN_WEIGHT', 'Maintain Weight'), ('GAIN_WEIGHT', 'Gain Weight'), ('BUILD_MUSCLE', 'Build Muscle')], default='MAINTAIN_WEIGHT', max_length=30)),
                ('dietary_preference', models.CharField(choices=[('VEGETARIAN', 'Vegetarian'), ('NON_VEGETARIAN', 'Non Vegetarian')], default='NON_VEGETARIAN', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergies', models.ManyToManyField(blank=True, related_name='profiles', to='profiles.allergy')),
                ('dietary_restrictions', models.ManyToManyField(blank=True, related_name='profiles', to='profiles.dietaryrestriction')),
                ('medical_conditions', models.ManyToManyField(blank=True, related_name='profiles', to='profiles.medicalcondition')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__email'],
            },
        ),
    ]
