# Generated by Django 6.0.6 on 2026-08-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialReligiousConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_religious_constraints',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.socialreligiousconstraint'),
        ),
    ]
