# Generated by Django 6.0.6 on 2026-08-24 12:17
from django.db import migrations

SOCIAL_RELIGIOUS_CONSTRAINTS = [
    {
        "name": "Shrawan Sombar Vrat",
        "description": "Fasting or dietary restrictions observed during Shrawan, particularly on Mondays.",
    },
    {
        "name": "Ekadashi",
        "description": "Dietary restrictions traditionally observed on Ekadashi fasting days.",
    },
    {
        "name": "Chaturmas",
        "description": "Seasonal religious dietary restrictions observed during the Chaturmas period.",
    },
    {
        "name": "Teej",
        "description": "Dietary practices and fasting restrictions associated with Teej observance.",
    },
    {
        "name": "Mourning / Kiriya / Death Rituals",
        "description": "Dietary restrictions followed during mourning and ritual observance periods.",
    },
    {
        "name": "No Onion / Garlic",
        "description": "Restriction against onion and garlic for religious, cultural, or personal reasons.",
    },
]


def seed_social_religious_constraints(apps, schema_editor):
    SocialReligiousConstraint = apps.get_model(
        "profiles",
        "SocialReligiousConstraint",
    )

    for item in SOCIAL_RELIGIOUS_CONSTRAINTS:
        SocialReligiousConstraint.objects.get_or_create(
            name=item["name"],
            defaults={
                "description": item["description"],
            },
        )


def reverse_seed_social_religious_constraints(apps, schema_editor):
    SocialReligiousConstraint = apps.get_model(
        "profiles",
        "SocialReligiousConstraint",
    )

    names = [item["name"] for item in SOCIAL_RELIGIOUS_CONSTRAINTS]

    SocialReligiousConstraint.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0003_socialreligiousconstraint_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            seed_social_religious_constraints,
            reverse_code=reverse_seed_social_religious_constraints,
        ),
    ]
