# Generated by Django 6.0.6 on 2026-08-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TotalFoodAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calories', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbs', models.FloatField(default=0)),
                ('total_fats', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='meals.meallog')),
            ],
            options={
                'verbose_name': 'Total Food Analysis',
                'verbose_name_plural': 'Total Food Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealFoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('food_quantity', models.FloatField(default=0)),
                ('food_quantity_unit', models.CharField(default='g', max_length=255)),
                ('food_calories', models.FloatField(default=0)),
                ('food_protein', models.FloatField(default=0)),
                ('food_carbs', models.FloatField(default=0)),
                ('food_fats', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='meals.totalfoodanalysis')),
            ],
            options={
                'verbose_name': 'Meal Food Item',
                'verbose_name_plural': 'Meal Food Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
