# Generated by Django 6.0.6 on 2026-08-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meallog_description_totalfoodanalysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_verdict', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('macro_assessment', models.JSONField(default=dict)),
                ('health_and_dietary_alerts', models.JSONField(default=list)),
                ('actionable_suggestions', models.JSONField(default=list)),
                ('alternative_foods', models.JSONField(default=list)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='meals.meallog')),
            ],
            options={
                'verbose_name': 'Meal Recommendation',
                'verbose_name_plural': 'Meal Recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
