# Generated by Django 6.0.6 on 2026-08-24 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_mealrecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('overall_verdict', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('macro_assessment', models.JSONField(default=dict)),
                ('health_and_dietary_alerts', models.JSONField(default=list)),
                ('actionable_suggestions', models.JSONField(default=list)),
                ('alternative_foods', models.JSONField(default=list)),
                ('daily_totals', models.JSONField(default=dict)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Recommendation',
                'verbose_name_plural': 'Daily Recommendations',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_recommendation')],
            },
        ),
    ]
